const { config } = require('../config');

// Template for the Single Copy flow (placeholder-based, supports optional follow-ups).
// The caller is expected to replace {placeholders} before sending to the model.
const COLD_EMAIL_PROMPT_WITH_FOLLOW_UP_TEMPLATE = [
	'You are an experienced B2B email copywriter.',
	'Based on the information provided, generate a {copy_length}-word cold email in a {tone_type} tone.',
	'Tone guidance (follow this exactly): {tone_guidance}',
	'Follow-up count: {follow_up_count}. If follow-up count is greater than 0, also generate that many follow-up emails to send after the initial email.',
	'Each follow-up should build on the previous message, be shorter than the last, and keep the overall tone consistent while becoming slightly more direct toward the final follow-up.',
	'If there is only one follow-up, it should feel like a polite, helpful nudge from a professional email marketer.',
	'',
	'Recipient details:',
	'- First name: {recipient_first_name}',
	'- Job title/role: {recipient_job_title}',
	'- Company: {recipient_company_name}',
	'- Website or activity context: {activity_text_or_URL_content_summary} (use this to personalize the message)',
	'',
	'Before writing the emails, first extract ONLY the most relevant personalization signals from the website/activity context (do NOT output this extraction):',
	'- 3–6 short bullets of concrete signals (e.g., what they do, who they serve, what they sell, a recent announcement, a key offer, a clear pain point, a growth signal).',
	'- Ignore boilerplate headings, navigation text, legal/footer content, and generic marketing fluff.',
	'- Use ONLY 1–2 of the strongest signals in the opening hook so it stays sharp and not cluttered.',
	'- Context over praise: avoid compliments/flattery like “Your work is impressive”. Instead, mention WHY you are reaching out based on ONE specific signal (examples: “official Holley dealer”, “specialises in roll-cage fabrication”, “recent expansion/hiring”, “new product line”).',
	'- The opening should NOT start with what you do (no “We help…”, “I’m with…”, “Our company…”). It should start with the prospect’s situation/goal implied by the signal (example: “Saw you’re expanding distribution to more Holley dealers…”).',
	'',
	'Offer details:',
	'- Value proposition/offer: {value_proposition}',
	'- Desired call-to-action: {call_to_action}',
	'',
	'Follow-up instructions (optional): {follow_up_prompts}',
	'',
	'Sender details:',
	'- Sender name: {sender_name}',
	'- Sender title: {sender_title}',
	'- Sender company: {sender_company}',
	'',
	'Subject (optional): {subject}',
	'',
	'Additional instructions (optional): {additional_instructions}',
	'',
	'Write a concise, natural-sounding cold email addressed to {recipient_first_name} that:',
	'• Includes a friendly greeting line at the start of EVERY email (initial + follow-ups): use “Hi {recipient_first_name},\n” if a first name is provided; otherwise use “Hi,\n”.',
	'• Opens with a personalized hook referencing their company or recent activity AND a concrete differentiator (no generic praise).',
	'• Frames the hook around the recipient’s likely goal/need (based on the context), not around your product or company.',
	'• Clearly explains how your offer helps them reach a reasonable goal.',
	'• Infer the most relevant goal/pain point from the context and your offer (do not ask the user for it).',
	'• Maintains the selected tone ({tone_type}) throughout, staying polite and respectful.',
	'• Includes the specified call-to-action ({call_to_action}) AND briefly restates the value of taking that step (e.g., “...to explore how a tailored prospect list could speed up your sales cycle”).',
	'• Ends with a professional sign-off using the sender details.',
	'',
	'For follow-up emails:',
	'- Start each follow-up with a brief, natural reference to the previous message so the recipient understands the context (no guilt, no pressure).',
	'- Keep follow-up content grounded in the extracted signals: any insight/observation must be traceable to the website/activity context. Do NOT introduce unrelated examples, products, or details that aren’t supported by the context.',
	'- Add genuinely NEW value so each follow-up repays the reader (do not just restate the offer). Choose ONE useful item, for example:',
	'  - A tailored suggestion tied to their signal (e.g., “If you’re expanding to X, one quick test is…”).',
	'  - A short checklist (3 bullets max) relevant to their goal.',
	'  - One concrete observation from their context + a practical next step.',
	'  - A general benchmark or best-practice framed carefully without claiming specific results or numbers (no made-up metrics).',
	'  - A brief “mini case pattern” without names, links, or invented facts (e.g., “When distributors add X, we often see Y friction…”).',
	'- Each follow-up must have its own NEW personalized subject that reflects the NEW piece of value in that follow-up (not the same subject as the initial email).',
	'- Follow-up subjects must be short (3–6 words) and specific (example: “Targeting Holley dealers for growth”); avoid generic subjects like “Checking in” or “Following up”.',
	'- Keep follow-ups shorter than the initial email and vary the call-to-action slightly to maintain interest.',
	'- Brevity target: each follow-up should be noticeably shorter than the previous email while still being clear. As a guideline, follow-ups are often ~50–75 words.',
	'- Use any provided follow-up prompts ({follow_up_prompts}) as guidance for tone or content.',
	'- Space follow-ups naturally; avoid sending too many follow-ups too quickly (deliverability/spam risk).',
	'- Keep the tone polite, friendly, and upbeat; avoid apologetic lines like “last try” or “sorry to bug you”.',
	'- Avoid signalling finality or abrupt closings (e.g., “Last note from me”, “final email”, “last attempt”). If you want to close the loop, do it positively and with permission (e.g., offer to share one quick example, ask if it’s not a priority right now, or ask whether you should close the loop).',
	'- Avoid pushy language and respect the prospect’s time.',
	'- End EVERY follow-up with a polite, positive close and a consistent professional sign-off (e.g., “Best,” or “Regards,”) using the sender details.',
	'',
	'Language & clarity rules:',
	'- Use simple, easy-to-understand English (roughly grade 6–8).',
	'- Use plain English; avoid industry jargon, acronyms, and buzzwords. If a ten-year-old wouldn’t understand a sentence, rewrite it.',
	'- Keep language realistic and straightforward; avoid exaggerated promises or urgent pressure.',
	'- Choose neutral alternatives to common spam trigger words when possible (e.g., “complimentary” instead of “free”).',
	'- Tone: conversational but professional. Write like you’re talking to a smart colleague. Use contractions when it sounds natural. Avoid stiff, corporate phrasing (avoid lines like “One more thought” or “Kindly advise”).',
	'- Write like a real person in a casual conversation: natural, direct, and friendly (but still B2B-appropriate).',
	'- Use short sentences, common words, and short paragraphs (easy to skim on mobile).',
	'- Avoid long, complex sentences and heavy punctuation.',
	'- No emojis. No exclamation marks. Avoid overly “salesy” adjectives.',
	'',
	'Subject line rules:',
	'- If the Subject field above is provided and not blank, use it exactly as the subject for the initial email ONLY.',
	'- For each follow-up email, ALWAYS generate a NEW, personalized subject (do not reuse the initial subject).',
	'- If the Subject field above is missing/blank for the initial email, generate a short subject (3–5 words) that reflects personalization and matches the selected tone.',
	'- For all generated subjects (initial when blank + every follow-up): keep it specific and personal — include either the company name OR a concrete signal from the context.',
	'- Avoid generic subjects like “Quick question”, “A brief question”, “Hello”, “Following up”.',
	'- Do NOT add reply/forward prefixes such as “Re:” or “Fwd:” (subjects must not start with these).',
	'',
	'Important delivery guidelines:',
	'- Avoid common spam trigger words and phrases (exaggerated financial promises, urgent pressure language like “limited time”/“act now”, generic greetings, and words like “free” or “100% guaranteed”).',
	'- Keep copy realistic and honest; do not promise unrealistic outcomes or over-the-top benefits.',
	'- Do not use ALL CAPS or excessive punctuation.',
	'- Limit hyperlinks: include no more than two links (including the signature) in each email, and avoid large images or attachments.',
	'- Do not invent links, domains, addresses, or case studies. Only include a link if it is explicitly provided in the inputs; otherwise, include no links.',
	'- Keep each email concise: the initial email should be about {copy_length} words; follow-ups must be shorter.',
	'- Keep grammar and spelling correct.',
	'- Ensure the email feels personal and genuine, not overly promotional.',
	'',
	'Output format:',
	'- Return plain text only (no JSON, no markdown).',
	'- For each email (initial and follow-ups), begin with a line: Subject: <subject text>.',
	'- Then a blank line, then the email body.',
	'- Separate each email with a blank line.',
]
	.join('\n');

function buildDeepSeekPrompt({
	firstName,
	lastName,
	company,
	website,
	scrapedContent,
	serviceFocus,
}) {
	const recipientName = [firstName, lastName].filter(Boolean).join(' ').trim();

	const ourServices = (serviceFocus || config.defaultServicesContext || '').trim();
	const peakLead = String(config.peakLeadServicesContext || '').trim();

	return [
		'Task: Write a high-performing B2B cold email that is concise, personalized, and NOT spammy.',
		'',
		'Inputs',
		`- Recipient name: ${recipientName || ''}`,
		`- Recipient company: ${company || ''}`,
		`- Website input (may be missing or expired): ${String(website || '').trim()}`,
		`- Website insights (scraped, may be noisy): ${String(scrapedContent || '').trim()}`,
		`- Our company name: ${config.ourCompanyName}`,
		ourServices ? `- Our services (primary): ${ourServices}` : null,
		peakLead ? `- Additional services context (secondary): ${peakLead}` : null,
		'',
		'Rules (follow strictly)',
		'0) Always personalize the first line: if a first name is provided, the opening_line MUST start with “{firstName}, ” (example: “Jeffery, …”).',
		'1) Personalization (context over praise): pick the BEST 1–2 concrete signals from the website insights (e.g., niche, offer, ICP, pricing/demo language, hiring/expansion). Use them in the opening line. Do not mention “I saw your website”. Do not flatter them.',
		'1c) Prospect-first opening: opening_line should NOT start with what we do or who we are (no “We help…”, “I’m with…”, “Our company…”). Start with the prospect’s situation/goal implied by the signal.',
		'1b) Subject MUST be personalized: include either the company name OR a concrete website signal (category/niche/offer). Avoid generic subjects like “Quick question”.',
		'2) No hallucinations: do NOT invent facts, customers, metrics, locations, or tech stack. If website insights are weak/empty, do NOT guess what they do. Use the company name and a general outbound/lead-gen pain instead.',
		'2b) If website insights are weak/empty, opening_line should still start with the first name and reference the company name (not their industry). Example: “Jeffery, quick question about how Kypreos Group is finding new projects this quarter.”',
		'3) Value: connect the website signal to ONE plausible pain point and ONE clear benefit tied to our services. Avoid feature lists.',
		'3b) No generic capability lines: do NOT write generic sentences like “VikiLeads specializes in…” or “We help teams like yours…”.',
		'3c) Instead, include ONE concrete “what we deliver + why it matters” sentence in the email_body. Format: deliverable → outcome. Example: “We can build a verified list of the right roles at the right companies, so your team spends less time researching and more time selling.”',
		'4) Brevity: total email must be 55–90 words. Max 3 short paragraphs. Short sentences.',
		'5) Simple English: write in easy, clear words (grade ~6–8). Avoid uncommon words, idioms, and overly formal phrasing.',
		'6) Tone: conversational but professional (like talking to a smart colleague). Use contractions when natural. No hype. No exclamation marks. No emojis.',
		'6) Spam words to avoid: free, guarantee/guaranteed, best, cheapest, act now, limited time, urgent, winner, risk-free, no-obligation, click here, buy now, 100%, $$$, unbelievable.',
		'6b) Approved proof points (optional, use at most ONE, and don’t add new numbers): 97% data accuracy, 50+ data sources, 10M+ contacts delivered, 500+ clients.',
		'7) CTA must appear ONLY once: do NOT include the CTA question inside opening_line or email_body. Put the question only in the cta field.',
		'8) CTA wording: do NOT always use “call”, “chat”, or “meeting”. Prefer neutral options like: “Open to 10 minutes next week?”, “Worth exploring?”, “Should I send 2 examples?”, or “Is this relevant for you?” Choose ONE.',
		'9) Output format: JSON only. No markdown. No extra keys. Use double quotes. Escape newlines as \\n inside strings.',
		'',
		'Output JSON schema (required keys)',
		'{',
		'  "subject": "(3–6 words; must include company name OR a concrete website signal; no hype)",',
		'  "opening_line": "(1 sentence; MUST start with recipient first name if provided; uses a specific website signal)",',
		'  "email_body": "(55–90 words total, 2–3 short paragraphs; do not repeat the opening_line verbatim; MUST NOT contain the CTA question)",',
		'  "cta": "(ONE question only; do not repeat; avoid always using call/chat/meeting)"',
		'}',
	]
		.filter(Boolean)
		.join('\n');
}

module.exports = { buildDeepSeekPrompt, COLD_EMAIL_PROMPT_WITH_FOLLOW_UP_TEMPLATE };
